AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  XRAY log Tracing POC

Parameters:
  paramEnvironment:
    Type: String
    Description: Which environment do you want to deploy to? (local, dev, test, or prod)
    AllowedValues:
      - dev
      - test
      - uat
      - stage
      - prod
  paramServiceName:
    Type: String
    Description: The name of the service
    Default: xray-tracing
  paramServiceApiName:
    Type: String
    Description: The name of the service
    Default: xray-tracing
  paramReleaseVersion:
    Type: String
    Description: The Release Version number
    Default: 0.1.0
  paramUserTableName:
    Type: String
    Description: User table name
    Default: user
  paramLogRetention:
    Type: Number
    Description: Log rentation in days
    Default: 14

Mappings:
  # The mappings section doesn't fully support Intrinsic functions like !Ref or !Sub
  # so values here need to be hard-coded instead of based on parameters.
  env:
    dev:
      invokeUrl: "https://mocki.io/v1/fafcf6b7-eb3b-4845-962a-134d0c499522"
    test:
      invokeUrl: "https://mocki.io/v1/fafcf6b7-eb3b-4845-962a-134d0c499522"
    uat:
      invokeUrl: "https://mocki.io/v1/fafcf6b7-eb3b-4845-962a-134d0c499522"
    stage:
      invokeUrl: "https://mocki.io/v1/fafcf6b7-eb3b-4845-962a-134d0c499522"
    prod:
      invokeUrl: "https://mocki.io/v1/fafcf6b7-eb3b-4845-962a-134d0c499522"

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 200
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Sub ${paramEnvironment}-xray-${paramUserTableName}
        URL: !FindInMap [env, !Ref paramEnvironment, invokeUrl]
        environmentName: !Ref paramEnvironment
        logLevel: info
        AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
    Tags:
      Application: !Ref paramServiceName
      Environment: !Ref paramEnvironment
      ReleaseVersion: !Ref paramReleaseVersion
    Tracing: Active

Resources:

  ## Lambda With API Gateway
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../functions/createUser
      Handler: index.handler 
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Layers: 
        - !Sub arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-nodejs-ver-0-24-0:2
        - !Ref NodeModules

  GetUserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../functions/getUserProfile
      Handler: index.handler 
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Layers: 
        - !Sub arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-nodejs-ver-0-24-0:2
        - !Ref NodeModules

  ## lambdaBasicExecution Role
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::Region}-${paramEnvironment}-${paramServiceName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  ## Lambda function Log group
  CreateUserLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: CreateUserFunction
    Properties:
      RetentionInDays: !Ref paramLogRetention
      LogGroupName: !Join ['',['/aws/lambda/',!Ref CreateUserFunction]]

  GetUserProfileLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: GetUserProfileFunction
    Properties:
      RetentionInDays: !Ref paramLogRetention
      LogGroupName: !Join ['',['/aws/lambda/',!Ref GetUserProfileFunction]]

  ## Lambda Layers
  NodeModules:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: node_modules
      Description: Node modules for all lambda
      ContentUri: ./layers
      Content:
        S3Bucket: !Sub ${paramEnvironment}_${AWS::Region}_node_modules
        S3Key: layer.zip
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x

  ## Data Source
  UserDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${paramEnvironment}-xray-${paramUserTableName}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 2

  ## Policy
  UserDBTablePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${paramEnvironment}-xray-${paramUserTableName}-policy
      Roles:
        - !Ref LambdaFunctionExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: '*'

  XrayTracesPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: xray-lambda-policy
      Roles:
        - !Ref LambdaFunctionExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
              - xray:GetSamplingStatisticSummaries
            Resource: '*'

  ## API Gateway
  ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties: 
        CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  APIGatewayRestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: Rest API to access resources
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Sub ${paramEnvironment}-${paramServiceApiName}

  UserAPIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    DependsOn: APIGatewayRestAPI
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt APIGatewayRestAPI.RootResourceId
      PathPart: user

  ProfileAPIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    DependsOn: APIGatewayRestAPI
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt APIGatewayRestAPI.RootResourceId
      PathPart: profile

  CreateUserMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn: UserAPIGatewayResource
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref UserAPIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserFunction}/invocations

  GetUserProfileMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn: ProfileAPIGatewayResource
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref ProfileAPIGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserProfileFunction}/invocations

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: ApiGatewayCloudWatchRole
    Properties:
      DeploymentId: !Ref APIGatewayDeployment
      Description: API gateway Stage
      RestApiId: !Ref APIGatewayRestAPI
      StageName: !Ref paramEnvironment
      AccessLogSetting: 
        DestinationArn: !GetAtt ApiGatewayAccessLogGroup.Arn
        Format: "{\"stage\":\"$context.stage\",\"request_id\":\"$context.requestId\",\"api_id\":\"$context.apiId\",\"resource_path\":\"$context.resourcePath\",\"resource_id\":\"$context.resourceId\",\"http_method\":\"$context.httpMethod\",\"source_ip\":\"$context.identity.sourceIp\",\"user-agent\":\"$context.identity.userAgent\",\"account_id\":\"$context.identity.accountId\",\"api_key\":\"$context.identity.apiKey\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"user_arn\":\"$context.identity.userArn\"}"
      TracingEnabled: true

  APIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CreateUserMethod
      - GetUserProfileMethod
    Properties:
      Description: API Gateway Deployment
      RestApiId: !Ref APIGatewayRestAPI

  CreateUserInvokePermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn: CreateUserFunction
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt CreateUserFunction.Arn
      Principal: apigateway.amazonaws.com

  GetUserProfileInvokePermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn: GetUserProfileFunction
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt GetUserProfileFunction.Arn
      Principal: apigateway.amazonaws.com

  ApiGatewayCloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref paramLogRetention
      LogGroupName: !Sub "/aws/apigateway/accesslogs/${paramEnvironment}-${paramServiceApiName}"

Outputs:
  CreateUserFunction:
    Description: "create new user lambda function ARN"
    Value: !GetAtt CreateUserFunction.Arn
  GetUserProfileFunction:
    Description: "Get user profile lambda function ARN"
    Value: !GetAtt GetUserProfileFunction.Arn
